name: API development Job Build

on:
  push:
    branches:
      - develop

env:
  AWS_DEFAULT_REGION: ${{secrets.AWS_DEFAULT_REGION}}
  AWS_IMAGE_REPOSITORY: ${{secrets.AWS_IMAGE_REPOSITORY}}
  PROJECT_ENVIRONMENT: "development"
  PROJECT_IMAGE_DOCKERFILE: "Dockerfile"
  IMAGE_SERVICE_NAME: "interface"

jobs:
  docker-build:
    if: ${{ false }} # Disable Job
    runs-on: ubuntu-20.04
    name: Ecs Build
    steps:
      - name: checkout code
        uses: actions/checkout@v2
        with:
          submodules: true
          persist-credentials: false
          ref: ${{ github.head_ref }}

      - name: Copy Make build
        run: cp  .build-utils/dockers/Makefile ./Makefile

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_DEFAULT_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build artifacts for project
        run: make docker-build-image

      - name: Push Image
        run: make docker-push-image

      - name: Deploy to Amazon ECS
        uses: ./.github/actions/ecs_deploys
        with:
          AWS_ACCOUNT_ID: ${{secrets.AWS_ACCOUNT_ID}}
          AWS_REGION: ${{secrets.AWS_DEFAULT_REGION}}
          AWS_IMAGE_REPOSITORY: ${{secrets.AWS_IMAGE_REPOSITORY}}
          CLUSTER_NAME: tracking-development
          SERVICE_NAME: interface
          DESIRED_COUNT: 1
          ENV_FILE: ./.env

#      - name: Update Schedule Amazon ECS Task
#        uses: ./.github/actions/schedule_task
#        with:
#          AWS_ACCOUNT_ID: ${{secrets.AWS_ACCOUNT_ID}}
#          AWS_REGION: ${{secrets.AWS_DEFAULT_REGION}}
#          CLUSTER_NAME: tracking-development
#          SERVICE_NAME: interface